name: Git Workshop Demo

on:
    push:
        branches:
            - 'feature/**'
            - 'bugfix/**'
            - 'chore/**'
            - main

env:
    SERVER_IP: '127.0.0.1'
    SERVER_PORT: 80
    REPO_NAME: ${{github.repository}}

jobs:
    job-1:
        runs-on: ubuntu-latest
        environment: development
        steps:
            - run: echo "hello github actions ${{github.actor}}"
            - run: echo "IP ${{env.SERVER_IP}} port ${{env.SERVER_PORT}}"
            - run: echo "${{env.REPO_NAME}}"
            - run: echo "${{vars.APP_NAME}}"
            - run: echo "${{secrets.API_KEY}}"
    job-2:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - run: echo "hello github actions ${{github.actor}}"
            - run: echo "IP ${{env.SERVER_IP}} port ${{env.SERVER_PORT}}"
            - run: echo "${{env.REPO_NAME}}"
            - run: echo "${{vars.APP_NAME}}"
            - run: echo "${{secrets.API_KEY}}"
              
        